### ISSUE TITLE
/help doesn't work

### ISSUE THREAD

**Issue by jimbo80008** [southstarangel/brokengears#1]
![help doesn't work](https://user-images.githubusercontent.com/64076931/80946669-d7c58380-8dee-11ea-94bc-1e4424c46ca3.PNG)

in server console /help doesn't work it gave the following error

**Comment by jimbo80008** [comment]
yeah so didn't label it propperly

**Comment by jimbo80008** [comment]
so yeah cant really label it for some reason

**Comment by southstarangel** [comment]
seems like some other mod is overwriting the command

**Comment by southstarangel** [comment]
fixed in 0.0.7 beta.
