### ISSUE TITLE
So i was trying to make a book...

### ISSUE THREAD

**Issue by jimbo80008** [southstarangel/brokengears#2]
i was trying to make the book for academycraft, and i tried to copy paste a recipy inside the book editor, the book crashed the world, and now i can't edit the book and have to do it all over again...
if there is a way to recover the book please let me know.
https://paste.dimdev.org/duhihejaco.mccrash

**Comment by southstarangel** [comment]
Send me the config folder of Enchiridion, this mod is very unstable and only some stuff really work.

**Comment by jimbo80008** [comment]
angel thanks for offering to help but i myself went into the json and removed the element that was copy pasted completely and that didn't fix it so i'll be making a new book, but at least i managed to get the text out that i already wrote which saves a lot of time
