### ISSUE TITLE
exception loop ticking is back

### ISSUE THREAD

**Issue by jimbo80008** [southstarangel/brokengears#3]
an old friend just crashed the server
![the return of an old friend](https://user-images.githubusercontent.com/64076931/81087554-2ad82d00-8efa-11ea-8206-77e9f16ddd8f.PNG)

**Comment by jimbo80008** [comment]
[crash-2020-05-05_14.47.04-server.txt](https://github.com/southstarangel/brokengears/files/4582933/crash-2020-05-05_14.47.04-server.txt)
crash report

**Comment by southstarangel** [comment]
Caused by ChunkGenLimiter mod. Removed it.
