### ISSUE TITLE
memory leaks

### ISSUE THREAD

**Issue by jimbo80008** [southstarangel/brokengears#4]
[21:56:55] [Server thread/DEBUG] [FML]: The world 5219b766 (world) may have leaked: seen 34495 times.
that shows up a lot, there seems to be a lot of memory leaks, not sure if this is something you can fix but for optimisation purposes i thought i would report it.

**Comment by southstarangel** [comment]
I'm rewriting the pack currently. Will be leaving out a lot of mods this time. Lets see if we can fix this.
